### ISSUE TITLE
paper link?

### ISSUE THREAD

**Issue by onlyonewater** [BioinfoMachineLearning/CDPred#1]
can you provide the paper link??

**Comment by ZhiYeG** [comment]
Thank you for your interest in our work. This article is about to be submitted for review, please be patient. We may post to bioRxiv and will let you know then.

**Comment by onlyonewater** [comment]
ok

**Comment by ZhiYeG** [comment]
> can you provide the paper link??
Hi, 
The paper now is available at bioRxiv : https://www.biorxiv.org/content/10.1101/2022.06.19.496734v1.

**Comment by onlyonewater** [comment]
> > can you provide the paper link??
> > Hi,
> > The paper now is available at bioRxiv : https://www.biorxiv.org/content/10.1101/2022.06.19.496734v1.

ok,thanks
