### ISSUE TITLE
About the training data

### ISSUE THREAD

**Issue by RujYin** [BioinfoMachineLearning/CDPred#2]
Hello,  
Do you provide your training data and features somewhere?  If not, may I have the dataset or the list if possible? Thx a lot!

**Comment by ZhiYeG** [comment]
> Hello, Do you provide your training data and features somewhere? If not, may I have the dataset or the list if possible? Thx a lot!

Hi, 
Please check the list of datasets under [example](https://github.com/BioinfoMachineLearning/CDPred/tree/main/example)/training_datalists/. And you can download all the structures from [PDB bank](https://www.rcsb.org/)

**Comment by LittletreeZou** [comment]
Hi, I am trying to use the data you released for my experiment. And I come across some questions about the data.

First, in the example/training_datalists/homodimer/, I notice some homodimers have the same chain ids. For example,  `4W98A_4W98A` contains two same chain id `A`. Is this normal? If the two chain ids are the same in a homodimer, how can you compute the contact map from a PDB file? 

Second, in the example/training_datalists/heterodimer/train.lst, it contains such data as follows:
```
4a8jC_4a8jE_1 245 204
4a8jC_4a8jE_2 245 204
```
What is the difference between the two examples?
