### ISSUE TITLE
how to train CDPred from scratch?

### ISSUE THREAD

**Issue by onlyonewater** [BioinfoMachineLearning/CDPred#3]
hi, how to train CDPred from scratch? you only provide inference code, where is the training code?

**Comment by onlyonewater** [comment]
@ZhiYeG

**Comment by ZhiYeG** [comment]
> hi, how to train CDPred from scratch? you only provide inference code, where is the training code?

Hi, we haven't arranged the training-related scripts yet, which should be updated later

**Comment by onlyonewater** [comment]
ok, When will you release the training code? Are there any plans?

**Comment by ZhiYeG** [comment]
The training code has been upload.
