### ISSUE TITLE
Question about training_datalists

### ISSUE THREAD

**Issue by LittletreeZou** [BioinfoMachineLearning/CDPred#5]
Hi, I am trying to experiment with the data you released. And I come across some questions about the data. 

First, in the example/training_datalists/homodimer/, I notice some homodimers have the same chain ids. For example,  `4W98A_4W98A` contains two same chain id `A`. Is this normal? If the two chain ids are the same in a homodimer, how can you compute the contact map from a PDB file? 

Second, in the example/training_datalists/heterodimer/train.lst, it contains such data as follows:
```
4a8jC_4a8jE_1 245 204
4a8jC_4a8jE_2 245 204
```
What is the difference between the two examples?

**Comment by ZhiYeG** [comment]
Hi, thanks for interesting in CDPred. For the homodimer, i.e.4W98, you can check the website https://www.rcsb.org/structure/4w98 and download the biological assembly1. In this file, it did contain two chain A, and sometime the same chain did can form one dimer in nature. As for the heterodimer, in order to enlarge the training datasets, for those dimer length larger than 350, I will random slide it down to the 350 or according to the largest dimer contact density (i.e. in a 350 dimer length contain the most inter-chain interactions). Let me know if you have any further question.

**Comment by LittletreeZou** [comment]
For homodimer cases like 4W98A_4W98A, the PDB file only contains one chain A, then if we want to compute the dimer distance maps,  I think the logic is
1.  extract coordinates of C_b (C_a for Glycine) for each chain A (the same when comparing across the first chain A and the second A)
2. compute the distance matrix based on the coordinates.

Based on this logic, then although we can do the calculation, the inter-chain distance matrix is just a copy of the intra-chain distance matrix， which is not what we expected. I wonder if maybe I miss something to compute the inter-chain distance given the coordinates of just a single chain. Could you please share how you cope with this problem?

**Comment by ZhiYeG** [comment]
> 

Hi, If you look at the biological assembly1 file of 4w98 on PDB bank. You can find out that two chains have the same structure individually. Still, the 3d coordinates in the homodimer structure are different, so you can directly extract coordinates from the homodimer PDB file.

**Comment by LittletreeZou** [comment]
YES! I find there is a BIOMT transformation in the pdb file which is used to get the coordinates of the second chain. I am a beginner in this field and I am not very familiar with the data. Thanks a lot for answering my questions.

**Comment by onlyonewater** [comment]
how to use the BIOMT transformation to get the coordinate of another chain? And where is the BIOMT transformation , I cannot find it

**Comment by onlyonewater** [comment]
**NOTE**: in homodimer dir, 6A4X and 3V8R have only one chain in the pdb file, so you need to download the raw file from PDB, and use BIOMT transformation to get coordinates of another chain.
