### ISSUE TITLE
ComplexDB.tar.gz can't be downloaded!

### ISSUE THREAD

**Issue by lkfo415579** [BioinfoMachineLearning/CDPred#6]
Following the instruction provided in here https://github.com/BioinfoMachineLearning/CDPred/tree/main/external_tool/ZComplexMSA

```wget http://sysbio.rnet.missouri.edu/CDPred_db/ComplexDB.tar.gz``` said 404 not found. Please reupload this data back to server again.

Thanks for your wonderful works.

**Comment by ZhiYeG** [comment]
Hi, thank you for being interested in our work. And sorry that our sysbio server was down due to the hacker attack. You can download the Unire90 from https://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/uniref90. fasta.gz, and I already uploaded the left database to CDPred/external_tool/ZComplexMSA/database/. Hope this work for you.

**Comment by jianlin-cheng** [comment]
Hi Zhiye,

Could you revise the readme file to ask users to download Unire90 from
https://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/uniref90? In
this way, they won't go to the broken link at the sysbio server.

Thanks.

Jack

**Comment by lkfo415579** [comment]
In the main page README, pssm required data ```wget http://sysbio.rnet.missouri.edu/CDPred_db/uniref90_01_2020.tar.gz``` don't  work as well.
It looks like a prepared blast database instead of fasta file.
Could you reupload the file as well?

**Comment by lkfo415579** [comment]
When I run inference command.
```python lib/Model_predict.py -n T1084A_T1084B -p ./example/T1084A_T1084B.pdb -a ./example/T1084A_T1084B.a3m -m homodimer -o ./output/T1084A_T1084B/```

It produces **ERROR!! Could not execute** error message, and the inexecutable command is on below.

```/opt/home/mimi/git/CDPred/bin/blast-2.2.26/bin/blastpgp -a 8 -e 0.001 -j 3 -h 0.002 -d /opt/home/mimi/big_data/uniref90 -i T1084A_T1084B.fasta -Q T1084A_T1084B.pssm```
I run this command alone and it outputs nothing, it is strange, Is my database not comparable with your database?

--
Solution:
1. download uniref90 from internet
2. /PATH/CDPred/bin/blast-2.2.26/bin/formatdb -t uniref90 -i /PATH/uniref90/uniref90.fasta -p T -o T # create blast-uniref90 db

This generated db can be used in the inference pipline.

**Comment by ZhiYeG** [comment]
I will upload the customed Uniref90 database on the zendo later. Currently, it hasn't been done due to a network issue. Once this is done I will update the readme file and let you know.

**Comment by ZhiYeG** [comment]
> In the main page README, pssm required data `wget http://sysbio.rnet.missouri.edu/CDPred_db/uniref90_01_2020.tar.gz` don't work as well. It looks like a prepared blast database instead of fasta file. Could you reupload the file as well?

The Uniref90 has been uploaded to the zendo, you can download it from https://zenodo.org/record/7591311#.Y9n9ZlvMJQM
