### ISSUE TITLE
Feature generate error

### ISSUE THREAD

**Issue by peter5842** [BioinfoMachineLearning/CDPred#7]
I have followed your README.md to run the examples. But I can't get the correct results.
I read the issues and make sure when I just run `CDPred/bin/blast-2.2.26/bin/blastpgp -a 8 -e 0.001 -j 3 -h 0.002 -d/Data/Databases/uniref90/uniref90 -i T1084A_T1084B.fasta -Q T1084A_T1084B.pssm >& T1084A_T1084B.psiblast.output`. It worked. What's wrong in there? Thank you!
[log.txt](https://github.com/BioinfoMachineLearning/CDPred/files/10703016/log.txt)

**Comment by ZhiYeG** [comment]
Are you download the Uniref90 from the zenodo or just prepare it yourself ?

**Comment by peter5842** [comment]
I have tried both, but the Uniref90 from the zenodo can't be unzipped, so I prepare it myself following the  #6 . (I have downloaded the database twice and got the same result)

**Comment by peter5842** [comment]
I have downloaded the Uniref90 twice and got the same result while unzipping it. So I prepared it in myself by following #6 and got this issue that I described.

❯ tar -jxvf uniref90_01_2020.tar.bz2
./uniref90_01_2020/
./uniref90_01_2020/uniref90.33.psq
./uniref90_01_2020/uniref90.19.pin
./uniref90_01_2020/uniref90.29.psi
./uniref90_01_2020/uniref90.29.phr
./uniref90_01_2020/uniref90.34.psq
./uniref90_01_2020/uniref90.27.psi
./uniref90_01_2020/uniref90.27.phr
./uniref90_01_2020/uniref90.10.pin
./uniref90_01_2020/uniref90.31.psd
./uniref90_01_2020/uniref90.20.psi
./uniref90_01_2020/uniref90.20.phr
./uniref90_01_2020/uniref90.17.pin
./uniref90_01_2020/uniref90.ssi
./uniref90_01_2020/uniref90.pal
./uniref90_01_2020/uniref90.04.psd
./uniref90_01_2020/uniref90.08.psq

bzip2: Data integrity error when decompressing.
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by ZhiYeG** [comment]
Sorry for the inconvenience, I will recompress it and update the zendo. Before that, I should do some tests on my local machine, I will update you once it has been done.

**Comment by ZhiYeG** [comment]
> I have downloaded the Uniref90 twice and got the same result while unzipping it. So I prepared it in myself by following #6 and got this issue that I described.
> 
> ❯ tar -jxvf uniref90_01_2020.tar.bz2 ./uniref90_01_2020/ ./uniref90_01_2020/uniref90.33.psq ./uniref90_01_2020/uniref90.19.pin ./uniref90_01_2020/uniref90.29.psi ./uniref90_01_2020/uniref90.29.phr ./uniref90_01_2020/uniref90.34.psq ./uniref90_01_2020/uniref90.27.psi ./uniref90_01_2020/uniref90.27.phr ./uniref90_01_2020/uniref90.10.pin ./uniref90_01_2020/uniref90.31.psd ./uniref90_01_2020/uniref90.20.psi ./uniref90_01_2020/uniref90.20.phr ./uniref90_01_2020/uniref90.17.pin ./uniref90_01_2020/uniref90.ssi ./uniref90_01_2020/uniref90.pal ./uniref90_01_2020/uniref90.04.psd ./uniref90_01_2020/uniref90.08.psq
> 
> bzip2: Data integrity error when decompressing. Input file = (stdin), output file = (stdout)
> 
> It is possible that the compressed file(s) have become corrupted. You can use the -tvv option to test integrity of such files.
> 
> You can use the `bzip2recover' program to attempt to recover data from undamaged sections of corrupted files.
> 
> tar: Unexpected EOF in archive tar: Unexpected EOF in archive tar: Error is not recoverable: exiting now

Hi, I already update the new zendo link of the uniref90 database, you can download it from "https://zenodo.org/record/7650566#.Y_Mbk1vMJQM"， and follow the readme file to unzip it.
